name: PrivateVaults
main: PrivateVault\main
author: Daniktheboss, fixed by Zeao.
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA6, 3.0.1]

commands:
  pv:
    description: "access private vaults"
    permission: pv

permissions:
  pv:
     default: true
     description: "Allows /pv"
