name: PrivateVaults
main: PrivateVaults\main
author: Daniktheboss
version: 1.0.0
api: [2.0.0, 3.0.0-ALPHA6, 3.0.1]

commands:
  pv:
    description: "access private vaults"
    permission: pv

permissions:
  pv:
     default: true
     description: "Allows /pv"
